.TH TTY\-COLORSCHEME "1" "April 2024" "tty\-colorscheme" "User Commands"
.hy 0
.SH NAME
tty\-colorscheme \- Colorschemes for the linux TTY
.SH SYNOPSIS
.B tty\-colorscheme
[\fB\-lcrsh\fR | \fIcolorscheme\fR]
.SH DESCRIPTION
A simple script to set colors in the linux TTY.
.SH OPTIONS
.TP
\fB\-l\fR
List colorschemes.
.TP
\fB\-c\fR
Print current palette.
.TP
\fB\-r\fR
Set a random colorscheme.
.TP
\fB\-s\fR
Shift through colorschemes using \fIj\fR and \fIk\fR keys.
.TP
\fB\-h\fR
Print help.
.SH EXAMPLES
.TP
\fB$ tty\-colorscheme\fR \fIaura\fR
Sets a colorscheme for the TTYs you are logged in.
.TP
\fB# tty\-colorscheme \-r\fR
Sets a random colorscheme for all TTYs despite user log on.
.SH CONFIGURATION
To change colors for a current TTY at user log on add \fBtty\-colorscheme\fR [\fIcolorscheme\fR] to your \fI~/.profile\fR.
It still requires using \fBsudo\fR(8) if you want to change colors across all TTYs.
If you get screen artifacts use \fBclear\fR(1) or hit \fIC\-l\fR. Use \fBreset\fR(1) to get back to the system default colors.
.SH CUSTOMIZATION
A colorscheme file looks like this:
.RS
.PP
color1=000000  # Black (Background)
.br
color2=F44336  # Red
.br
color3=4CAF50  # Green
.br
color4=FFEB3B  # Yellow
.br
color5=2196F3  # Blue
.br
color6=9C27B0  # Magenta
.br
color7=00BCD4  # Cyan
.br
color8=9E9E9E  # White (Foreground)
.br
color9=000000  # Black
.br
color10=F44336 # Red
.br
color11=4CAF50 # Green
.br
color12=FFEB3B # Yellow
.br
color13=2196F3 # Blue
.br
color14=9C27B0 # Magenta
.br
color15=00BCD4 # Cyan
.br
color16=9E9E9E # White
.RE
.PP
Just change the hex values of colors and put it in the colorschemes directory.
.SH FILES
.TP
\fI/etc/tty\-colorscheme/colorschemes\fR
Default directory for colorscheme files.
