#!/bin/bash

set -euo pipefail

[[ "$(id -u)" -ne 0 ]] && exec sudo "${0}" "${@}"

bin_dir="/usr/bin"
config_dir="/etc/tty-colorscheme/colorschemes"
man_dir="/usr/share/man/man1"
service_dir="/usr/lib/systemd/system"

check_depends() {
    pkgs=("file" "gzip")
    missing_pkgs=""

    for pkg in "${pkgs[@]}"; do
        [[ -x "$(command -v "${pkg}")" ]] || missing_pkgs="${missing_pkgs} ${pkg}"
    done

    if [[ -n "${missing_pkgs}" ]]; then
        printf "Install the following packages:%s\n" "${missing_pkgs}"
        exit 1
    fi
}

install_files() {
    install -vDm 644 tty-colorscheme/colorschemes/*/* -t "${config_dir}"
    install -vm 755 tty-colorscheme/tty-colorscheme -t "${bin_dir}"
    install -vm 644 tty-colorscheme/tty-colorscheme.1 -t "${man_dir}"

    gzip -vf "${man_dir}/tty-colorscheme.1"

    if [[ -x "$(command -v systemctl)" ]]; then
        install -vm 644 tty-colorscheme/tty-colorscheme.conf -t "${config_dir}"
        install -vm 644 tty-colorscheme/tty-colorscheme.service -t "${service_dir}"

        printf "\nRun \"systemctl enable tty-colorscheme\" to apply colors on boot"
        printf "\nColorscheme can be set in /etc/tty-colorscheme/tty-colorscheme.conf\n\n"
    fi
}

remove_files() {
    rm -vrf "${config_dir}"
    rm -vf "${bin_dir}/tty-colorscheme"
    rm -vf "${man_dir}/tty-colorscheme.1.gz"

    [[ -x "$(command -v systemctl)" ]] && rm -vf "${service_dir}/tty-colorscheme.service"
}

case "${1:-}" in
    "remove")
        remove_files
        ;;
    "")
        check_depends
        install_files
        ;;
esac
