#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf '\nYou must run this script as root to install tty-colorscheme and themes\n'
	printf 'Pass remove arg to uninstall\n\n'
	exit 1
fi

if [ -z "$1" ]; then
	install -vm 755 tty-colorscheme/tty-colorscheme -t /usr/bin
	install -vDm 644 tty-colorscheme/colorschemes/gogh/* -t /etc/tty-colorscheme/colorschemes
	install -vDm 644 tty-colorscheme/colorschemes/extra/* -t /etc/tty-colorscheme/colorschemes
	if [ -x "$(command -v systemctl)" ]; then
		install -vm 644 systemd/tty-colorscheme.conf -t /etc/tty-colorscheme
		install -vm 644 systemd/tty-colorscheme.service -t /usr/lib/systemd/system
		printf '\nEnable tty-colorscheme.service to change tty colors on boot\n'
		printf 'Colorscheme can be set in /etc/tty-colorscheme/tty-colorscheme.conf\n\n'
	fi
elif [ "$1" = remove ]; then
	rm -vf /usr/bin/tty-colorscheme
	rm -vrf /etc/tty-colorscheme
	if [ -x "$(command -v systemctl)" ]; then
		rm -vf /usr/lib/systemd/system/tty-colorscheme.service
	fi
fi
