#!/bin/sh

colorschemes_dir=/etc/tty-colorscheme/colorschemes

print_help() {
	printf 'Usage: %s [-lpcrh | colorscheme]\n' "$(basename "$0")"
	printf '  -l    list colorschemes\n'
	printf '  -p    list colorschemes and print their palettes\n'
	printf '  -c    print current palette\n'
	printf '  -r    set a random colorscheme\n'
	printf '  -h    print help\n'
}

if [ $# -eq 0 ]; then
	PRINT_HELP=1
fi

while getopts :lpcrh opt; do
	case $opt in
		l) PRINT_SCHEMES=1;;
		p) PRINT_SCHEMES_PALETTES=1;;
		c) PRINT_CURRENT_PALETTE=1;;
		r) SET_RANDOM_COLORSCHEME=1;;
		h) PRINT_HELP=1;;
		*) printf 'Invalid option -%s\n' "$OPTARG" && print_help && exit 1;;
	esac
done

shift $((OPTIND-1))

if [ -n "$PRINT_SCHEMES" ] || [ -n "$PRINT_SCHEMES_PALETTES" ]; then
	for scheme_file in "$colorschemes_dir"/*; do
		scheme_name=$(basename "$scheme_file")
		printf '%s\n' "$scheme_name"
		if [ -n "$PRINT_SCHEMES_PALETTES" ]; then
			cnt=0
			while IFS= read -r line || [ -n "$line" ]; do
				eval "$line"
				hex_color=${line#*=}
				r=${hex_color%"${hex_color#??}"}
				g=${hex_color#"${r}"}
				g=${g%"${g#??}"}
				b=${hex_color#"${r}${g}"}
				printf '\e[48;2;%d;%d;%dm   \e[0m' 0x"$r" 0x"$g" 0x"$b"
				cnt=$((cnt+1))
				if [ $((cnt % 8)) -eq 0 ]; then
					printf '\n'
				fi
			done < "$scheme_file"
		fi
	done
fi

if [ -n "$PRINT_CURRENT_PALETTE" ]; then
	cnt=0
	for bkgrnd in $(seq 40 47); do
		printf '%b' "\033[${bkgrnd}m"
		for bold in 22 1; do
			printf '%b' "\033[${bold}m"
			for frgrnd in $(seq 30 37); do
				cntprt=$cnt
				while [ ${#cntprt} -lt 3 ]; do
					cntprt=" $cntprt"
				done
				printf '%b' "\033[${frgrnd}m $cntprt"
				cnt=$((cnt+1))
			done
		done
		printf '%b\n' '\033[0m'
	done
fi

if [ -n "$PRINT_HELP" ]; then
	print_help
fi

if [ "$OPTIND" -eq 1 ] && [ -n "$1" ] || [ -n "$SET_RANDOM_COLORSCHEME" ]; then
	if [ -n "$SET_RANDOM_COLORSCHEME" ]; then
		colorscheme=$(basename "$(find "$colorschemes_dir" -type f | shuf -n 1)")
	else
		colorscheme=$1
		if [ ! -f "$colorschemes_dir/$colorscheme" ]; then
			printf 'Invalid colorscheme\n'
			exit 1
		fi
	fi
	while IFS= read -r line || [ -n "$line" ]; do
		eval "$line"
	done < "$colorschemes_dir/$colorscheme"
	set_tty_colors() {
		printf '\e]P0%s' "${color1:?}"  # Background
		printf '\e]P1%s' "${color2:?}"  # Red
		printf '\e]P2%s' "${color3:?}"  # Green
		printf '\e]P3%s' "${color4:?}"  # Yellow
		printf '\e]P4%s' "${color5:?}"  # Blue
		printf '\e]P5%s' "${color6:?}"  # Magenta
		printf '\e]P6%s' "${color7:?}"  # Cyan
		printf '\e]P7%s' "${color8:?}"  # White
		printf '\e]P8%s' "${color9:?}"  # Black
		printf '\e]P9%s' "${color10:?}" # Red
		printf '\e]PA%s' "${color11:?}" # Green
		printf '\e]PB%s' "${color12:?}" # Yellow
		printf '\e]PC%s' "${color13:?}" # Blue
		printf '\e]PD%s' "${color14:?}" # Magenta
		printf '\e]PE%s' "${color15:?}" # Cyan
		printf '\e]PF%s' "${color16:?}" # White
	}
	for i in $(seq 1 6); do
		set_tty_colors > /dev/tty"$i"
	done
	if [ "$TERM" = linux ]; then
		clear
	fi
	printf 'Setting %s colorscheme\n' "$colorscheme"
fi
