#!/bin/bash

find ../tty-colorscheme/colorschemes -type f -exec sha256sum {} + > checksums.txt
list_dups() {
	awk '{print $1}' checksums.txt | sort | uniq -d | while read -r dup; do grep "${dup}" checksums.txt; done
}

echo -en "\nDuplicate files:\n"
list_dups

echo -en "\nDuplicates removed:\n"
list_dups | awk 'NR % 2 == 1 {print $2}' | while read -r line; do rm -vf "${line}"; done
