#!/bin/bash

./01-update-gogh
./02-make-hex-uppercase
./03-find-dup-names
./04-find-and-remove-dups

echo -en "\nPress Enter to continue\n" && read -r

rm -vrf Gogh-* converted-gogh-schemes checksums.txt ./*.tar.gz
