#!/bin/sh

colorschemes_dir="/etc/tty-colorscheme/colorschemes"

print_help() {
    printf "Usage: %s [-lps | colorscheme]\n" "$(basename "$0")"
    printf "  -l    list colorschemes\n"
    printf "  -p    print current palette\n"
    printf "  -s    shift through colorschemes\n"
}

list_colorschemes() {
    for scheme_file in "${colorschemes_dir}"/*; do
        basename "${scheme_file}"
    done
}

print_current_palette() {
    cnt=0
    for bkgrnd in 40 41 42 43 44 45 46 47; do
        printf "\e[%sm" "${bkgrnd}"
        for bold in 22 1; do
            printf "\e[%sm" "${bold}"
            for frgrnd in 30 31 32 33 34 35 36 37; do
                printf "\e[%sm %3s" "${frgrnd}" "${cnt}"
                cnt="$((cnt+1))"
            done
        done
        printf "\e[0m\n"
    done
}

shift_colorschemes() {
    # No quoting
    set -- $(list_colorschemes)
    max_ind="$#"
    i=1
    while true; do
        colorscheme="$(eval "printf \"\${${i}}"\")"
        $(basename "$0") "${colorscheme}"
        printf "\nPress Enter to go to the next colorscheme"
        printf "\nPress b and then Enter to go one colorscheme back\n"
        read -r char
        case "${char}" in
            b) [ "${i}" -gt 1 ] && i="$((i-1))" ;;
            *) [ "${i}" -lt "${max_ind}" ] && i="$((i+1))" ;;
        esac
    done
}

set_colorscheme() {
    colorscheme_file="${colorschemes_dir}/$1"
    [ ! -f "${colorscheme_file}" ] && printf "Invalid colorscheme: %s\n" "$1" && exit 1
    while IFS= read -r line || [ -n "${line}" ]; do
        eval "${line}"
    done < "${colorscheme_file}"
    set_tty_colors() {
        printf "\e]P0%s" "${color01:?}" # Black (Background)
        printf "\e]P1%s" "${color02:?}" # Red
        printf "\e]P2%s" "${color03:?}" # Green
        printf "\e]P3%s" "${color04:?}" # Yellow
        printf "\e]P4%s" "${color05:?}" # Blue
        printf "\e]P5%s" "${color06:?}" # Magenta
        printf "\e]P6%s" "${color07:?}" # Cyan
        printf "\e]P7%s" "${color08:?}" # White (Foreground)
        printf "\e]P8%s" "${color09:?}" # Black
        printf "\e]P9%s" "${color10:?}" # Red
        printf "\e]PA%s" "${color11:?}" # Green
        printf "\e]PB%s" "${color12:?}" # Yellow
        printf "\e]PC%s" "${color13:?}" # Blue
        printf "\e]PD%s" "${color14:?}" # Magenta
        printf "\e]PE%s" "${color15:?}" # Cyan
        printf "\e]PF%s" "${color16:?}" # White
    }
    for i in 1 2 3 4 5 6; do
        set_tty_colors > "/dev/tty${i}"
    done > /dev/null 2>&1
    [ "${TERM}" = "linux" ] && clear && $(basename "$0") -p
    printf "Setting %s colorscheme" "$1"
}

while getopts ":lps" opt; do
    case "${opt}" in
        l)
            list_colorschemes
            exit 0
            ;;
        p)
            print_current_palette
            exit 0
            ;;
        s)
            shift_colorschemes
            exit 0
            ;;
        *)
            printf "Invalid option -%s\n" "${OPTARG}"
            print_help
            exit 1
            ;;
    esac
done

[ "$#" -eq 1 ] && set_colorscheme "$1" && exit 0

print_help
