.TH TTY\-COLORSCHEME "1" "August 2025" "tty\-colorscheme" "User Commands"
.hy 0
.SH NAME
tty\-colorscheme \- Colorschemes for the linux TTY
.SH SYNOPSIS
.B tty\-colorscheme
[\fB\-cfps\fR | \fIcolorscheme\fR]
.SH DESCRIPTION
A simple script to set colors in the linux TTY.
.SH OPTIONS
.TP
\fB\-c\fR
List colorschemes.
.TP
\fB\-f\fR
List PSF fonts.
.TP
\fB\-p\fR
Print current palette.
.TP
\fB\-s\fR
Shift through colorschemes using \fIj\fR and \fIk\fR keys. Shift through fonts using \fIh\fR and \fIl\fR keys.
.SH EXAMPLES
.TP
\fB$ tty\-colorscheme\fR \fIaura\fR
Apply the \fIaura\fR colorscheme to the current TTY.
.TP
\fB# tty\-colorscheme\fR \fIhybrid\fR
Apply the \fIhybrid\fR colorscheme to all TTYs.
.SH CONFIGURATION
To change colors for a current TTY at user log in add \fBtty\-colorscheme\fR [\fIcolorscheme\fR] to your \fI~/.profile\fR.
It requires using \fBsudo\fR(8) if you want to change colors across all TTYs.
If you get screen artifacts use \fBclear\fR(1) or hit \fIC\-l\fR. Use \fBreset\fR(1) to get back to the system default colors.
TTY font can also be set with \fBsetfont\fR(8).
.SH CUSTOMIZATION
A colorscheme file looks like this:
.RS
.PP
color01="000000" # Black (Background)
.br
color02="F44336" # Red
.br
color03="4CAF50" # Green
.br
color04="FFEB3B" # Yellow
.br
color05="2196F3" # Blue
.br
color06="9C27B0" # Magenta
.br
color07="00BCD4" # Cyan
.br
color08="9E9E9E" # White (Foreground)
.br
color09="000000" # Black
.br
color10="F44336" # Red
.br
color11="4CAF50" # Green
.br
color12="FFEB3B" # Yellow
.br
color13="2196F3" # Blue
.br
color14="9C27B0" # Magenta
.br
color15="00BCD4" # Cyan
.br
color16="9E9E9E" # White
.RE
.PP
Just change the hex values of colors and put it in the colorschemes directory.
.SH FILES
.TP
\fI/etc/tty\-colorscheme/colorschemes\fR
Default directory for colorscheme files.
