.TH TTY\-COLORSCHEME "1" "November 2025" "tty\-colorscheme" "User Commands"
.hy 0
.SH NAME
tty\-colorscheme \- Colorschemes for the Linux TTY
.SH SYNOPSIS
.B tty\-colorscheme
[\fIoption\fR | \fIcolorscheme\fR]
.SH DESCRIPTION
A simple script to set colors in the Linux TTY.
.SH OPTIONS
.TP
\fB\-l\fR
List available colorschemes.
.TP
\fB\-f\fR
List available PSF fonts.
.TP
\fB\-p\fR
Print the current palette.
.TP
\fB\-c\fR
Cycle through colorschemes and fonts using \fIj\fR/\fIk\fR and \fIh\fR/\fIl\fR keys.
.SH EXAMPLES
.TP
\fB$ tty\-colorscheme\fR \fIaura\fR
Apply the \fIaura\fR colorscheme to the current TTY.
.TP
\fB# tty\-colorscheme\fR \fIhybrid\fR
Apply the \fIhybrid\fR colorscheme to all TTYs.
.SH CONFIGURATION
Changing colors across all TTYs requires \fBsudo\fR(8).
If you encounter screen artifacts, press \fICtrl+L\fR or type \fBclear\fR(1).
To revert to the system default colors, type \fBreset\fR(1).
The TTY font can also be changed using \fBsetfont\fR(8).
To apply a colorscheme automatically upon login, add \fBtty\-colorscheme\fR <\fIcolorscheme\fR> to your \fI~/.profile\fR.
.SH CUSTOMIZATION
A colorscheme file has the following format:
.RS
.PP
color01="000000" # Black (Background)
.br
color02="F44336" # Red
.br
color03="4CAF50" # Green
.br
color04="FFEB3B" # Yellow
.br
color05="2196F3" # Blue
.br
color06="9C27B0" # Magenta
.br
color07="00BCD4" # Cyan
.br
color08="9E9E9E" # White (Foreground)
.br
color09="000000" # Black
.br
color10="F44336" # Red
.br
color11="4CAF50" # Green
.br
color12="FFEB3B" # Yellow
.br
color13="2196F3" # Blue
.br
color14="9C27B0" # Magenta
.br
color15="00BCD4" # Cyan
.br
color16="9E9E9E" # White
.RE
.PP
To create a custom colorscheme, modify the HEX values and place the file in the directory with colorscheme files.
.SH FILES
.TP
\fI/etc/tty\-colorscheme/colorschemes\fR
Default directory for colorscheme files.
