#!/bin/bash

set -euo pipefail

cs_dir="/etc/tty-colorscheme/colorschemes"

_warn_cs() {
    [[ -z "${cs_arr:-}" ]] && printf "No colorschemes found\n" 1>&2
}

_warn_fnt() {
    [[ -z "${fnt_arr:-}" ]] && printf "No PSF fonts found\n" 1>&2
}

_get_schemes() { # Only output full file name
    find "${cs_dir}"/* 2> /dev/null | awk -F/ '{print $NF}'
}

_get_fonts() { # Only output full file name
    fnt_dirs=(
        "/usr/share/consolefonts" # Debian
        "/usr/share/kbd/consolefonts" # Arch
        "/usr/lib/kbd/consolefonts" # Fedora
    )

    for fnt_dir in "${fnt_dirs[@]}"; do
        if [[ -d "${fnt_dir}" ]]; then
            find "${fnt_dir}" -name "*.psf*.gz" \
                | awk -F/ '{print $NF}' \
                | sort -V
        fi
    done
}

_fill_cs_arr() {
    mapfile -t cs_arr < <(_get_schemes)
}

_fill_fnt_arr() {
    mapfile -t fnt_arr < <(_get_fonts)
}

_set_colors() {
    # Black   Red     Green   Yellow  Blue    Magenta Cyan    White
    # color01 color02 color03 color04 color05 color06 color07 color08
    # color09 color10 color11 color12 color13 color14 color15 color16

    printf "\e]P0%s\e]P1%s\e]P2%s\e]P3%s\e]P4%s\e]P5%s\e]P6%s\e]P7%s" \
           "${color01:?}" "${color02:?}" "${color03:?}" "${color04:?}" \
           "${color05:?}" "${color06:?}" "${color07:?}" "${color08:?}"

    printf "\e]P8%s\e]P9%s\e]PA%s\e]PB%s\e]PC%s\e]PD%s\e]PE%s\e]PF%s" \
           "${color09:?}" "${color10:?}" "${color11:?}" "${color12:?}" \
           "${color13:?}" "${color14:?}" "${color15:?}" "${color16:?}"
}

_set_font() {
    fnt="${1}"

    if [[ "$(id -u)" -eq 0 ]]; then
        for i in {1..6}; do setfont "${fnt}" -C "/dev/tty${i}"; done
    else
        setfont "${fnt}"
    fi

    clear
    showconsolefont

    printf "Setting font: %s\n\n" "${fnt%%.*}"
}

list_schemes() {
    _fill_cs_arr
    _warn_cs && exit 1
    printf "%s\n" "${cs_arr[@]}"
}

list_fonts() {
    _fill_fnt_arr
    _warn_fnt && exit 1
    printf "%s\n" "${fnt_arr[@]%%.*}"
}

print_palette() {
    cnt="1"
    for bkgrnd in {40..47}; do
        printf "\e[%sm" "${bkgrnd}"
        for bold in 22 1; do
            printf "\e[%sm" "${bold}"
            for frgrnd in {30..37}; do
                printf "\e[%sm %3s" "${frgrnd}" "${cnt}"
                ((cnt++))
            done
        done
        printf "\e[0m\n"
    done
}

cycle_through() {
    _fill_cs_arr
    max_idx_cs="$((${#cs_arr[@]} - 1))"
    idx_cs="-1"

    _fill_fnt_arr
    max_idx_fnt="$((${#fnt_arr[@]} - 1))"
    idx_fnt="-1"

    mode=""
    clear

    while true; do
        case "${mode}" in
            "cs")
                # Only process if index is valid
                if [[ "${idx_cs}" -ge 0 && "${idx_cs}" -le "${max_idx_cs}" ]]; then
                    set_scheme "${cs_arr[${idx_cs}]}"
                    printf "[%s/%s]\n" "$((idx_cs + 1))" "$((max_idx_cs + 1))"
                else
                    clear
                    _warn_cs
                fi
                ;;

            "fnt")
                # Only process if index is valid
                if [[ "${idx_fnt}" -ge 0 && "${idx_fnt}" -le "${max_idx_fnt}" ]]; then
                    _set_font "${fnt_arr[${idx_fnt}]}"
                    printf "[%s/%s]\n" "$((idx_fnt + 1))" "$((max_idx_fnt + 1))"
                else
                    clear
                    _warn_fnt
                fi
                ;;
        esac

        printf "\nUse j/k keys to cycle through colorschemes\n"
        printf "Use h/l keys to cycle through fonts\n"

        read -rsn1
        case "${REPLY}" in
            "j")
                mode="cs"
                if [[ "${idx_cs}" -lt "${max_idx_cs}" ]]; then
                    : $((idx_cs++))
                else
                    idx_cs="0" # Wrap around to the first element
                fi
                ;;

            "k")
                mode="cs"
                if [[ "${idx_cs}" -gt 0 ]]; then
                    ((idx_cs--))
                elif [[ "${idx_cs}" -eq -1 ]]; then
                    idx_cs="0" # Get to the first element on first keypress
                else
                    idx_cs="${max_idx_cs}" # Wrap around to the last element
                fi
                ;;

            "l")
                mode="fnt"
                if [[ "${idx_fnt}" -lt "${max_idx_fnt}" ]]; then
                    : $((idx_fnt++))
                else
                    idx_fnt="0" # Wrap around to the first element
                fi
                ;;

            "h")
                mode="fnt"
                if [[ "${idx_fnt}" -gt 0 ]]; then
                    ((idx_fnt--))
                elif [[ "${idx_fnt}" -eq -1 ]]; then
                    idx_fnt="0" # Get to the first element on first keypress
                else
                    idx_fnt="${max_idx_fnt}" # Wrap around to the last element
                fi
                ;;

            *)
                exit 0
                ;;
        esac
    done
}

set_scheme() {
    cs="${1}"

    if [[ ! -f "${cs_dir}/${cs}" ]]; then
        printf "Invalid colorscheme: %s\n" "${cs}" 1>&2
        exit 1
    fi

    unset color{01..16}
    source "${cs_dir}/${cs}"

    for i in {01..16}; do
        color_var="color${i}"

        if [[ ! -v "${color_var}" ]]; then
            printf "Missing %s in scheme %s\n" "${color_var}" "${cs}" 1>&2
            exit 1
        fi

        if ! [[ "${!color_var}" =~ ^[0-9A-Fa-f]{6}$ ]]; then
            printf "Invalid value for %s in scheme %s: %s\n" "${color_var}" "${cs}" "${!color_var}" 1>&2
            exit 1
        fi
    done

    if [[ "$(id -u)" -eq 0 ]]; then
        for i in {1..6}; do _set_colors > "/dev/tty${i}"; done
    else
        _set_colors
    fi

    # Prevent palette going into logs
    if [[ "${TERM}" == "linux" ]]; then
        clear
        print_palette
    fi

    printf "\nSetting colorscheme: %s\n\n" "${cs}"
}

cs_print_help() {
    progname="${0##*/}"

    printf "Usage: %s <option | colorscheme>\n" "${progname}"
    printf "  -l    List available colorschemes\n"
    printf "  -f    List available PSF fonts\n"
    printf "  -p    Print the current palette\n"
    printf "  -c    Cycle through colorschemes and fonts\n"

    tty | grep -q tty || printf "%s should be run from TTY\n" "${progname}" 1>&2
}

if [[ "${#}" -gt 1 ]]; then
    printf "Only 1 option or 1 argument is accepted\n" 1>&2
    cs_print_help
    exit 1
elif [[ "${#}" -eq 0 ]]; then
    cs_print_help
    exit 0
fi

case "${1}" in
    "-l")
        list_schemes
        ;;

    "-f")
        list_fonts
        ;;

    "-p")
        print_palette
        ;;

    "-c")
        cycle_through
        ;;

    "-"*)
        printf "Invalid option: %s\n" "${1}" 1>&2
        print_help
        exit 1
        ;;

    *)
        set_scheme "${1}"
        ;;
esac
