#!/bin/bash

# A tool for converting Gogh schemes for tty-colorscheme.
# TTY background is color1 and foreground is color8.
# color9 and color16 are the same but for reversed colors.

gogh_ver=327
gogh_link="https://github.com/Gogh-Co/Gogh/archive/refs/tags/v$gogh_ver.tar.gz"

curl -LO $gogh_link
tar xvf v$gogh_ver.tar.gz
mkdir -v converted-schemes-gogh
sleep 1

for scheme_file in Gogh-"$gogh_ver/installs/"*.sh; do
	get_colors() {
		awk -F '#' '
		/BACKGROUND_COLOR/ { printf "color01=%s\n", substr($2, 1, 6) }
			/COLOR_02/ { printf "color02=%s\n", substr($2, 1, 6) }
			/COLOR_03/ { printf "color03=%s\n", substr($2, 1, 6) }
			/COLOR_04/ { printf "color04=%s\n", substr($2, 1, 6) }
			/COLOR_05/ { printf "color05=%s\n", substr($2, 1, 6) }
			/COLOR_06/ { printf "color06=%s\n", substr($2, 1, 6) }
			/COLOR_07/ { printf "color07=%s\n", substr($2, 1, 6) }
		/FOREGROUND_COLOR/ { printf "color08=%s\n", substr($2, 1, 6) }
		/BACKGROUND_COLOR/ { printf "color09=%s\n", substr($2, 1, 6) }
			/COLOR_10/ { printf "color10=%s\n", substr($2, 1, 6) }
			/COLOR_11/ { printf "color11=%s\n", substr($2, 1, 6) }
			/COLOR_12/ { printf "color12=%s\n", substr($2, 1, 6) }
			/COLOR_13/ { printf "color13=%s\n", substr($2, 1, 6) }
			/COLOR_14/ { printf "color14=%s\n", substr($2, 1, 6) }
			/COLOR_15/ { printf "color15=%s\n", substr($2, 1, 6) }
		/FOREGROUND_COLOR/ { printf "color16=%s\n", substr($2, 1, 6) }
		' "$scheme_file" | sort -V
	}
	echo "Converting $(basename "$scheme_file" .sh)"
	get_colors > "converted-schemes-gogh/$(basename "$scheme_file" .sh)"
done

# c64 dirs are completely unreadable
echo 'Fixing c64'
sed -i 's|color05=40318D|color05=7869C4|' converted-schemes-gogh/c64
sed -i 's|color13=40318D|color13=7869C4|' converted-schemes-gogh/c64
sleep 1

rm -vf ../tty-colorscheme/colorschemes/gogh/*
cp -vf converted-schemes-gogh/* ../tty-colorscheme/colorschemes/gogh

echo 'Completed'
