#!/bin/bash

set -euo pipefail

if [[ ! -f "$(pwd)/update-gogh-and-check" ]]; then
    printf "Run this script from \"scripts\" directory\n"
    exit 1
fi

update_gogh() {
    gogh_ver="362"
    gogh_link="https://github.com/Gogh-Co/Gogh/archive/refs/tags/v${gogh_ver}.tar.gz"
    cs_dir="../tty-colorscheme/colorschemes"
    gogh_dir="${cs_dir}/gogh"
    tmp_dir="converted-gogh-schemes"

    curl -LO "${gogh_link}"
    tar xvf "v${gogh_ver}.tar.gz"
    mkdir -vp "${tmp_dir}"

    for scheme_path in "Gogh-${gogh_ver}/installs/"*.sh; do
        scheme_file="${scheme_path##*/}"
        scheme_short="${scheme_file%%.*}"

        printf "Converting %s\n" "${scheme_short}"

        awk -F '#' '
        /BACKGROUND_COLOR/ {printf "color01=\"%s\"\n", substr($2,1,6)}
                /COLOR_02/ {printf "color02=\"%s\"\n", substr($2,1,6)}
                /COLOR_03/ {printf "color03=\"%s\"\n", substr($2,1,6)}
                /COLOR_04/ {printf "color04=\"%s\"\n", substr($2,1,6)}
                /COLOR_05/ {printf "color05=\"%s\"\n", substr($2,1,6)}
                /COLOR_06/ {printf "color06=\"%s\"\n", substr($2,1,6)}
                /COLOR_07/ {printf "color07=\"%s\"\n", substr($2,1,6)}
        /FOREGROUND_COLOR/ {printf "color08=\"%s\"\n", substr($2,1,6)}
        /BACKGROUND_COLOR/ {printf "color09=\"%s\"\n", substr($2,1,6)}
                /COLOR_10/ {printf "color10=\"%s\"\n", substr($2,1,6)}
                /COLOR_11/ {printf "color11=\"%s\"\n", substr($2,1,6)}
                /COLOR_12/ {printf "color12=\"%s\"\n", substr($2,1,6)}
                /COLOR_13/ {printf "color13=\"%s\"\n", substr($2,1,6)}
                /COLOR_14/ {printf "color14=\"%s\"\n", substr($2,1,6)}
                /COLOR_15/ {printf "color15=\"%s\"\n", substr($2,1,6)}
        /FOREGROUND_COLOR/ {printf "color16=\"%s\"\n", substr($2,1,6)}
        ' "${scheme_path}" | sort -V > "${tmp_dir}/${scheme_short}"
    done

    # Fix c64 scheme, dirs are unreadable
    sed -i 's|color05="40318D"|color05="7869C4"|' "${tmp_dir}/c64"
    sed -i 's|color13="40318D"|color13="7869C4"|' "${tmp_dir}/c64"

    rm -vf "${gogh_dir}"/*
    cp -vf "${tmp_dir}"/* "${gogh_dir}"
}

make_hex_uppercase() {
    for cs_file in "${cs_dir}"/*/*; do
        sed -i 's/=\(.*\)/=\U\1/' "${cs_file}"
    done
}

find_dup_names() {
    printf "\nDuplicate names:\n"
    find "${cs_dir}" -type f -printf "%p %f\n" \
        | sort -k2 \
        | uniq -f1 --all-repeated=separate
}

remove_dup_files() {
    find "${cs_dir}" -type f -exec sha256sum {} \; > checksums.txt

    list_dup_files() {
        awk '{print $1}' checksums.txt \
            | sort \
            | uniq -d \
            | while read -r dup; do
                  grep "${dup}" checksums.txt
              done \
            | sort -V
    }

    printf "\nDuplicate files:\n"
    list_dup_files

    printf "\nDuplicates removed:\n"
    list_dup_files \
        | awk 'NR % 2 == 0 {print $2}' \
        | while read -r line; do
              rm -vf "${line}";
          done
}

clean_up() {
    printf "\nPress Enter to continue\n" && read -r
    rm -vrf Gogh-* "${tmp_dir}" checksums.txt ./*.tar.gz
}

update_gogh
make_hex_uppercase
find_dup_names
remove_dup_files
clean_up
